### ISSUE TITLE
This seems typo

### ISSUE THREAD

**Issue by chiroito** [rh-jmc-team/jfr-datasource#51] opened 2020-02-13 09:03 UTC
https://github.com/rh-jmc-team/jfr-datasource/blob/0f3cc6cf0eb6bba5a1c5751957890f892571c5f2/server/src/main/java/com/redhat/jfr/events/RecordingService.java#L85

**Comment by jiekang** [comment] 2020-03-07 22:04
The simplejson sample API [1] has incoming type "timeserie"

[1] https://grafana.com/grafana/plugins/grafana-simple-json-datasource
```
[...]
  "targets": [
     { "target": "upper_50", "refId": "A", "type": "timeserie" },
[...]
```

So closing as not a bug.

**Closed by jiekang** 2020-03-07 22:04 UTC
